import { Metadata } from 'next';
import axios from 'axios';

type Props = {
    params: Promise<{ projectId: string }>;
    children: React.ReactNode;
};

export async function generateMetadata({ params }: Props): Promise<Metadata> {
    const { projectId } = await params;
    const apiBase = process.env.NEXT_PUBLIC_API_URL;

    if (!apiBase) {
        return { title: 'Shared Project | Webyrix' };
    }

    try {
        const response = await fetch(`${apiBase}/api/projects/${projectId}`, {
            next: { revalidate: 60 }
        });

        if (!response.ok) {
            return {
                title: 'Project Preview | Webyrix',
                description: 'View this design generated by Webyrix.'
            };
        }

        const resData = await response.json();
        const project = resData.data;

        if (!project) return { title: 'Project Not Found | Webyrix' };

        return {
            title: `${project.description || 'Shared Project'} | Webyrix`,
            description: `Check out this design generated by Webyrix. ${project.description || ''}`,
            openGraph: {
                title: `${project.description || 'Shared Project'} | Webyrix`,
                description: `Check out this design generated by Webyrix. ${project.description || ''}`,
                images: ['/logo.svg'],
            },
            twitter: {
                card: 'summary_large_image',
                title: `${project.description || 'Shared Project'} | Webyrix`,
                description: `Check out this design generated by Webyrix. ${project.description || ''}`,
                images: ['/logo.svg'],
            }
        };
    } catch (error) {
        return {
            title: 'Shared Project | Webyrix',
            description: 'A professional design generated by Webyrix.'
        };
    }
}

export default function ProjectViewLayout({ children }: { children: React.ReactNode }) {
    return <>{children}</>;
}
